# -*- coding: utf-8 -*-
"""The manual quality sign-offs for the v2 main board (PCB_QUALITY.md M1-M42).

This is `BOARD_NOTES["quality"]["manual"]`, lifted out of elec/main.py because
thirty-eight pieces of evidence would have doubled that file and buried the
circuit in it. Everything else about the board still lives beside its number
there; this is the one place where the subject IS the evidence.

HOW TO SIGN. One entry each, against a PRIMARY source -- a datasheet section, a
maker drawing, a fab rule page -- or against a measurement taken off the ROUTED
board. An item with no evidence is LEFT OUT of this dict with the reason it is
open recorded in OPEN below, because "signed" has to mean something. PCB_QUALITY
splits these into "must hold" (signable only by showing it is true, else the
board changes) and "decide" (signable by showing it is done, or by recording the
decision not to do it -- which is not the same as skipping it).

Datasheets this board is signed against, with the revision actually read:

    TI SNVSAA5B    LMR14020, Feb 2015 rev Dec 2024
    TI SLUSAY4D    UCC27516/UCC27517, Mar 2012 rev Dec 2014
    Espressif      ESP32-WROOM-32E/32UE datasheet v2.1
    Bourns         SRN6045TA series, Electrical Specifications @ 25 C
    Littelfuse     SMBJ series (SMBJ24A)
    Phoenix        MKDS 3/2-5,08 and PT 1,5/N-3,5-H drawings
    JLCPCB         PCB capabilities page, read 2026-10-04 -- also the FAB table
                   in cadkit/pcbflow/quality.py, which A12 measures against
"""
from __future__ import annotations

# ── Why the items that are NOT in MANUAL are not in it ──────────────────────
# Not a to-do list in the loose sense: each of these names the specific thing
# that is missing, so it can be closed by doing that thing and not by writing
# more prose. Several are blocked on the same two facts -- that 13 values are
# unsourced (elec/fab.py OPEN_VALUES), and that this board has not been
# ordered -- and those are stated once each rather than thirteen times.
OPEN = {
    "M12": "the order has not been placed. No part number has been read off a "
           "listing today, nothing has been stock-checked, and the rotations "
           "have not been through JLCPCB's previewer -- which is the step the "
           "package's own ROTATION-CHECK.txt exists to make someone do. The "
           "board name and revision ARE in silk (M31). 13 of 32 BOM lines are "
           "unsourced; elec/fab.py refuses to call the package orderable and "
           "lists them.",

    "M30": "not costed. The assembly tier has not been chosen, the count of "
           "extra-fee part lines is not known, and the price breaks have not "
           "been checked against this outline -- 95 x 100 mm is inside "
           "JLCPCB's cheapest size tier today, which is why the board was not "
           "grown when it ran short of room, but 'inside a tier' is not the "
           "same as having read the current price table. What IS known and "
           "will cost: the five terminal blocks and J6 are through-hole, so "
           "either a THT surcharge or hand soldering (CIRCUIT.md section 7 "
           "chooses hand soldering), and 13 values are unsourced, which "
           "decides nothing about tier until they are parts. Blocked on the "
           "same thing as M12.",

    "M42": "lifecycle not checked, and it cannot be faked from here. No "
           "part's active/NRND status has been read, no lead time looked at, "
           "and the 13 unsourced values in elec/fab.py have no part number to "
           "check -- that file is deliberately the gate that fails a build "
           "whose value is neither sourced, nor a generic passive, nor listed "
           "open, so a changed part cannot slip through as 'just another open "
           "item'. Named alternates exist for exactly one line (CIRCUIT.md "
           "section 2 lists the buck's), and the parts that have a "
           "'do-not-substitute' reason carry it (M40). What HAS been done is "
           "the rule's last clause, the distinct-part-number census: A11 "
           "checks one value one spelling across 16 values, and this pass "
           "collapsed every bare '100n' onto a single 100n/50V rather than "
           "adding a third rating (M4). Blocked on the same thing as M12.",
}

MANUAL = {
    # ══ must hold ═══════════════════════════════════════════════════════════
    "M15": (
        "signed on a BOUND rather than on a curve, and the bound is stated so "
        "it can be checked later. Three parts to this rule. (1) ESR inside the "
        "datasheet's range: the LMR14020 is internally compensated and "
        "publishes no ESR stability window, only the ripple relation of "
        "equation 11 -- which at a 20 mV target wants ESR under 36 mOhm, and "
        "two 1206 X7R ceramics in parallel are about 2.5. (2) Effective "
        "capacitance read off the maker's DC-bias curve: NOT DONE, because C4 "
        "and C19 are the generic value '22u/16V' and there is no maker behind "
        "them to have a curve. What stands in for it is a bound that holds for "
        "any part meeting the value -- equation 13 at the brownout-driven "
        "undershoot ceiling asks 16.5 uF, and 44 uF nominal taken down by a "
        "pessimistic 0.6 derate is 26.4, a factor of 1.60. That bound is the "
        "whole argument, so the dielectric is now a REQUIREMENT and not an "
        "assumption: X7R or better, recorded as do-not-substitute under M40, "
        "because a Y5V of the same marking can lose 80 % and land at 8.8 uF -- "
        "under the requirement, with nothing in any gate to notice. When C4 "
        "and C19 become part numbers the curve should be read and the 0.6 "
        "checked. (3) Headroom: a buck from a 15-20 V pack to 3.3 V has 11.7 V "
        "at the flat end of the pack, so dropout is not a question on this "
        "board. The capacitance itself was SHORT before this pass -- C4's "
        "22 uF alone cleared eq 13 by 1.33x nominal and not at all derated, "
        "which is why there are two now (see M13 and the BUCK_COUT block). "
        "Note what this is NOT signed against: 7.2.2.4's closing sentence that "
        "'one 47 uF output capacitor is needed at least' has no equation "
        "behind it and sits inside a 5 V / 2 A worked example, so it is not a "
        "general floor anybody can check -- 44 uF landing beside it is "
        "reassurance, not evidence."
    ),
    "M16": (
        "both halves, and the half that stayed open was waiting for a number "
        "it does not need. "
        "The ring half, unchanged and still the tighter of the two: the pack "
        "is docked live at the Makita holder, so VBAT IS a cable-fed input. "
        "2 x 20 V = 40 V against the lowest absolute maximum on that net, U1's "
        "44 V VIN (SNVSAA5B 5.1), leaves 4 V -- it passes, but on the "
        "RECOMMENDED maximum of 40 V it passes by nothing at all, which is why "
        "the damping is not optional here. It is fitted: C1/C2 are 100 uF "
        "ELECTROLYTICS rather than bare ceramics, so the LC that would ring is "
        "damped by their ESR, and the SMBJ24A clamps at 38.9 V underneath it. "
        "The inrush half. This entry used to say the surge 'has not been "
        "computed against their rating, because the dock is not part of this "
        "repo and its contact rating has not been read'. The first clause is "
        "true and the conclusion does not follow, because neither quantity "
        "that matters depends on the contact. "
        "ENERGY DOES NOT DEPEND ON ANY RESISTANCE. Docking charges every "
        "capacitor on VBAT from zero: C1 and C2 at 100 uF each, C17 at 10, "
        "C15 at 4u7, and C18 at 10 -- 224.7 uF, counting C18 even though it "
        "sits behind F1 and is current-limited by the PTC rather than by the "
        "contacts, because counting it is the conservative direction. "
        "0.5*C*V^2 at 20 V is 0.0449 J, and that is the whole make-arc budget "
        "however the loop resistance divides up. "
        "AND THE I2t IS BOUNDED OVER EVERY RESISTANCE THAT CAN EXIST. For an "
        "RC charge I2t = V^2*C/(2R), so the LOWEST loop resistance is the "
        "worst case rather than the best. 60 mOhm is used, which is already "
        "below what two electrolytics' ESR, the harness and a pair of blade "
        "contacts can be between them -- a deliberate floor, not an estimate. "
        "That gives 0.749 A2s, with a 333 A peak decaying on a 13.5 us time "
        "constant. "
        "THE COMPARISON NEEDS NO DATASHEET EITHER, which is the step that was "
        "missing. An I2t expressed as the protection's OWN rated current says "
        "how long that current would have to flow to do the same heating: "
        "0.749 A2s is 7.5 ms of 10 A, and the off-board 10 A ATC fuse in the "
        "+ lead carries 10 A indefinitely. So the inrush is inside the fuse "
        "unconditionally -- there is no fuse curve under which 7.5 ms of its "
        "own rated current opens it. Both figures are arithmetic in "
        "elec/main.py with asserts that fire if the bound ever stops being "
        "self-evident: over 100 ms equivalent, or over 0.5 J of arc, and the "
        "ratings have to be read after all. "
        "THE RESIDUAL, named rather than lumped: the dock's own contact MAKE "
        "rating is still unread, so 0.0449 J of capacitive arc is bounded but "
        "not compared to a published figure. What makes that acceptable rather "
        "than a gap is that the make is not the binding case for those "
        "contacts -- the same two blades carry this machine's 7.5 A pump "
        "current continuously, and up to 15 A if a future firmware ever runs "
        "both pumps together, so their steady duty is far harsher than a 13.5 "
        "us capacitive transient. If the dock's rating is ever read, the "
        "number to check it against is 0.0449 J on make."),
    "M18": (
        "there are two crossings on this board and only one of them could "
        "ever back-power, so that one got the resistor the rule names. J6 "
        "pin 4 goes straight to the module's U0RXD: an adapter can hold it at "
        "3.3 V while this board's own 3V3 is down -- the pack out of the dock, "
        "which is the ordinary way someone programs it -- and the current then "
        "runs through the pin's ESD diode into a 52 uF rail. J6 pin 1 is +3V3, "
        "so the INTENDED use is for the adapter to power the board, which is "
        "why it has never bitten; but landing only TX/RX/GND is a normal thing "
        "to do, and this rule is about what CAN happen. M18 names the fix -- "
        "'a series resistor, a powered-off-tolerant buffer or guaranteed "
        "sequencing' -- and R25 is 1k in series with ESP_RX, holding the diode "
        "current to about 2.7 mA. It costs nothing at 115200 baud: 1k into the "
        "pin's 2 pF plus a little trace is tens of nanoseconds against an "
        "8.7 us bit, and 1k is already a value on this board (R22, R24) so it "
        "adds no part number. It sits at the CONNECTOR end, where the hazard "
        "enters, so the whole run back to the module is behind it. The other "
        "crossing is safe by construction and needs nothing: the level sensor "
        "runs at VBAT and its output is an open collector, so it can only pull "
        "DOWN and cannot feed the 3V3 rail at all -- R23 is the pull-up, and "
        "that open collector is also what keeps 18 V off the pin."
    ),
    "M13": (
        "re-laid against SNVSAA5B 7.4.1 and measured against it afterwards, "
        "which is the comparison this rule asks for. It also found the thing "
        "the comparison existed to find: the LMR14020 integrates ONE switch, "
        "a 90 mOhm HIGH-SIDE MOSFET, and this board had no catch diode at all "
        "-- guidelines 4 and 5 both refer to 'the diode D', 6.3 says 'the "
        "high-side MOSFET is off and the external low side diode conducts', "
        "and 7.2.2.5 is a whole section on selecting it. D6 is now fitted "
        "(SCHOTTKY-60V-3A, SMA). Every distance in the cluster, before -> "
        "after, in millimetres pad to pad: CIN to VIN 4.43 -> 3.80 and CIN to "
        "the GND pin 5.44 -> 3.80, which are now EQUAL because VIN (pin 2) and "
        "GND (pin 7) sit directly opposite at dy +0.635, 4.95 mm apart across "
        "the body, so a bridging ceramic has a floor and centring it above the "
        "package is what reaches that floor; bootstrap cap 14.01 -> 4.90; "
        "switch node 11.61 -> 7.05; FB pin to the divider's tap 6.07 -> 1.77 "
        "and to R1's tap 10.93 -> 2.73, with the whole FB node now 3.85 mm of "
        "track; inductor output to COUT 10.36 -> 2.85; RT 17.67 -> 2.30; SS "
        "17.08 -> 4.33. The new commutation loop is 7.39 mm of track outside "
        "the parts, with the diode's two legs balanced at 3.60 and 3.80 mm. "
        "Guideline 1's second half, the sense path kept off the noise, is "
        "measured too: the nearest FB track comes 3.56 mm to a SW track and "
        "the nearest +3V3 track 3.53 mm, neither of them adjacent. The switch "
        "node is no bigger than it must be and is not a heatsink -- it is a "
        "track, not a pour. Two deliberate deviations, both named: D6 takes "
        "the place beside pins 7 and 8 and L1 the next one out, which costs "
        "the switch node about 3.5 mm, because the diode is the part that "
        "COMMUTATES and guideline 3's own reason for keeping the inductor "
        "close is radiated noise rather than loop area; and RT and SS are in "
        "none of the six guidelines, both carrying microamps into a timing "
        "pin, so C14 at 4.33 mm gives up nothing the datasheet asked for. "
        "Smallest courtyard gap in the cluster is 0.230 mm and every gap is "
        "positive."
    ),
    "M1": (
        "six connectors, each pin order declared ONCE in elec/main.py's "
        "gen.part call and nowhere else. Five are wire-entry terminals, so "
        "there is no mating half to disagree with and nothing can be plugged "
        "in reversed; the sixth (J6) is a 1x06 2.54 header that a jumper CAN "
        "be reversed on, which is why kicad_silk prints its whole pinout on "
        "B.Silk beside the footprint's own pin-1 marker -- measured on the "
        "board as '1 +3V3 / 2 GND / 3 ESP_TX_TO_PROG / 4 ESP_RX_FROM_PROG / "
        "5 EN / 6 IO0', so the direction is on the silk and not only in the "
        "head of whoever wired it (M26). The board-to-firmware half is held "
        "by tools/check_pin_map.py, which reads the GPIO numbers out of "
        "firmware/src/main.cpp and out of elec/main.py and retypes neither. "
        "Entry faces: elec/CIRCUIT.md section 7, with the one face that is "
        "convention rather than measurement named under M32."
    ),
    "M2": (
        "measured off the placed footprints rather than assumed, because the "
        "two conventions in play point opposite ways. KiCad concentrates the "
        "polarity graphics on the MARKED end: on D1/D4/D5 that is the pad-1 "
        "side (F.Fab carries 18.48 / 10.34 / 10.34 mm of line there against "
        "6.55 / 3.10 / 3.10 mm on the pad-2 side), so pad 1 is the cathode "
        "band; on C1/C2 it is the pad-2 side (29.50 mm against 13.33), so "
        "pad 1 is the positive terminal. Checked against what the nets ask "
        "for: D1 pad 1 = VBAT (a unidirectional TVS's cathode belongs on the "
        "positive rail), D5 pad 1 = VGATE (shunt Zener), D4 pad 1 = +3V3 with "
        "its anode on BUZZ_DRV so it conducts when the buzzer's inductance "
        "drives the collector up, C1/C2 pad 1 = VBAT. D2/D3 are the exception "
        "and are declared {1:A, 2:K, 3:A2} deliberately: TO-263-2's pad 2 is "
        "the tab, measured at 9.40 x 10.80 mm against the outer leads' "
        "4.60 x 1.10, and a single-cathode D2PAK Schottky's tab is the "
        "cathode. The fab-side re-check is each package's ROTATION-CHECK.txt, "
        "which lists exactly the polarised and pin-1-bearing placements."
    ),
    "M4": (
        "every ceramic states its rating now, and every rating is at least 2x "
        "its rail -- which two of them were not. C13 was 10u/16V on the 10 V "
        "VGATE rail, 1.6x, and is now 10u/25V; C9/C10, the two UCC27517 "
        "bypasses, were a bare '100n' with no rating at all on that same 10 V "
        "rail and are now 100n/50V along with every other 100n on the board, "
        "which keeps A11's one-value-one-spelling and costs nothing because "
        "50 V is what a commodity 0603 X7R already is. The rest, against "
        "their rails: C15 4u7/50V and C1/C2 100u/50V on a 20 V pack (2.5x), "
        "C17 10u/50V on the same (5x), C4 22u/16V and C5/C6/C16 10u/16V on "
        "3.3 V (4.8x). Regulator capacitance per SNVSAA5B: a ceramic AT VIN "
        "-- C15, 4.43 mm from pin 2, the part that was simply absent before "
        "and left 38 mm of track as the buck's input loop -- and 32 uF of "
        "output. Step loads: the two 100 uF electrolytics are at the pump "
        "terminals, which is what A2 measures at 24.91 and 24.94 mm against "
        "its 25 mm limit. Effective capacitance under DC bias is the one part "
        "that cannot be closed yet; it is stated under M15."
    ),
    "M5": (
        "the worst case on VBAT is the TVS's clamp, so that is the single "
        "number every part on the rail is judged against -- and it is read "
        "off the table rather than rounded from memory, which is how it had "
        "come to be written as '39.0, approx'. Littelfuse SMBJ24A: 24 V "
        "standoff, 26.7 V minimum breakdown, VC = 38.9 V MAX at IPP = 15.5 A, "
        "600 W. Against 38.9 V: U1's VIN/EN absolute maximum is 44 V "
        "(SNVSAA5B 5.1), leaving 5.1 V; its RECOMMENDED maximum is 40 V "
        "(5.3), leaving 1.1 V; the pump FETs' required Vds is 60 V, leaving "
        "21.1 V. The buck is the weakest thing on that node and the only "
        "assert there used to couple the clamp to the FETs, which have the "
        "most margin of the three -- so the TVS is what keeps U1 inside its "
        "datasheet, and there are three asserts now rather than one. Raising "
        "the clamp by 1.2 V fails one of them. The gate side: VGATE is 10 V "
        "into a UCC27517 rated 20 V absolute and 18 V recommended (SLUSAY4D "
        "8.1, 8.3) and into a gate rated +-20 V, and IN+ sees 3.3 V against a "
        "20 V input absolute maximum the datasheet notes 'is not restricted "
        "by the voltage on the VDD pin'. The 3V3 rail: the ESP32's absolute "
        "maximum is 3.6 V (v2.1 table 13) against a divider asserted to set "
        "3.301 V. R9 was the one part whose own rating nothing checked -- "
        "67 mW at a fresh pack against an 0805's 125 mW, 54 %, now asserted, "
        "and the reason R9 is the only 0805 resistor on the board. Heat is "
        "M25."
    ),
    "M7": (
        "each IC against its own datasheet's application section. U1, "
        "SNVSAA5B: the feedback divider is 100k/29k4 on a VFB of 0.750 V typ "
        "(5.5) for 3.301 V, written as arithmetic with an assert so the "
        "comment can no longer disagree with the parts -- it used to say "
        "3.3 V and set 3.12; RT/SYNC is 49k9, the datasheet's own table value "
        "for 500 kHz, on a pin 6.3.8 says 'can't be left floating or shorted "
        "to ground' and which was floating; SS is 10 nF for a defined 2.5 ms "
        "ramp where floating leaves it to stray capacitance and 3 uA; BOOT "
        "carries 100 n; EN is tied to VIN so the buck runs whenever the pack "
        "is on; the exposed pad is on GND, which the datasheet requires in "
        "those words -- 'must be connected to ground plane on PCB'. The "
        "inductor is sized by the datasheet's own equation and its own "
        "saturation instruction (M14). U3/U4, SLUSAY4D: IN- is tied to GND, "
        "which the datasheet asks for -- 'the unused input pin is not left "
        "floating and must be properly biased to ensure that driver output is "
        "enabled' -- and which is also the asserted state of the active-low "
        "input; VDD is bypassed 3.05 mm from pin 1. U2: EN has the 10k/1u RC "
        "for power-on reset, and all FOUR of the module's ground pins are on "
        "GND -- 1, 15, 38 and the underside pad 39, where 15 and 39 had been "
        "on no net at all, which no unconnected count can see. No crystal "
        "sits on this board; the 40 MHz one is inside the module, so its load "
        "capacitors are not this design's to get wrong."
    ),
    "M8": (
        "the ESP32's five strapping pins, against table 4 of the WROOM-32E "
        "datasheet v2.1 -- which states that the defaults hold when a pin is "
        "'not connected to any circuit, or connected to an external "
        "high-impedance circuit', and gives the internal pull resistance as "
        "45 kOhm typ (table 15). GPIO0, pull-up, default 1: this board's only "
        "load on it is J6 pin 6, an open header, so the default holds, and "
        "table 6 gives SPI Boot for GPIO0 = 1 with GPIO2 at any value. GPIO2, "
        "pull-down, 0: unconnected. MTDI/GPIO12, pull-down, 0: unconnected, "
        "which is the state that leaves the internal VDD_SDIO at 3.3 V -- "
        "pulling it UP selects 1.8 V and the module's own flash stops "
        "reading, so this is a pin where doing nothing is the requirement. "
        "MTDO/GPIO15, pull-up, 1: unconnected, so U0TXD boot printing stays "
        "enabled, which is what you want on a board whose only console is J6. "
        "GPIO5, pull-up, 1: unconnected, and nothing here uses SDIO. EN is "
        "the one strap this board drives, through R3 to 3V3 with C8 for the "
        "ramp, and J6 pin 5 brings it out so an adapter's DTR can reset the "
        "part. The only open-drain line on the board is the level sensor's "
        "output, and R23 pulls it up (M34)."
    ),
    "M14": (
        "SNVSAA5B 7.2.2.3 says it in these words -- 'The inductor current "
        "rating must be higher than current limit', because 'during an "
        "instantaneous short or over current operation event, the RMS and "
        "peak inductor current can be high'. The limit is ILIMT 2.5 / 3.2 / "
        "3.8 A min/typ/max (5.5), so the number to beat is 3.8. The part "
        "fitted was SRN6045TA-150M, Isat 3.80 A TYP -- equal to the maximum "
        "limit, and equal to the typical at that, so half the reel saturates "
        "below a fault the regulator is entitled to hold indefinitely. L1 is "
        "now SRN6045TA-100M: 10 uH +-20 %, DCR 52 mOhm, Irms 3.20 A, Isat "
        "4.60 A, which clears it -- and TI's own worked example in that same "
        "section pairs the same limit with '3 A RMS current and 4 A "
        "saturation current', so this is not a strict reading. The fix ran "
        "DOWN in inductance, which is the counter-intuitive part: in this "
        "series Isat falls as L rises, so 22 uH (3.30 A) and 33 uH (2.50 A) "
        "are both worse. Normal running: 0.551 A peak-to-peak ripple at a "
        "20 V pack, so a 0.876 A peak at the 0.6 A load against 4.60 A of "
        "Isat, 5.3x, and still in CCM (Imin 0.33 A). K_IND is 0.28 of the "
        "part's rated 2 A, inside the datasheet's 20-40 %. Read Bourns' own "
        "definitions before comparing any of this to another maker: this "
        "series quotes Isat at a 30 % inductance drop, LOOSER than the common "
        "20 %, and Irms at a 40 C rise rather than 20. All three couplings "
        "are asserts in elec/main.py, and the 15 uH part trips the first one."
    ),
    "M19": (
        "VGATE is 10 V and the FET requirement is Rds(on) <= 10 mOhm AT 4.5 V "
        "Vgs, so the part is driven at better than twice the voltage its "
        "on-resistance is specified at. That requirement exists in that form "
        "because 3V3 was once the only rail here and could not have produced "
        "it -- the UCC27517 is a 4.5-18 V part and its own UVLO would have "
        "held both outputs low, so both pumps would have been dead even with "
        "the pinout right. Off in reset, three independent ways: the driver "
        "'Output Held Low When Input Pins Are Floating' (SLUSAY4D feature "
        "list) and is held low through VDD UVLO, its IN- is tied to GND so "
        "the enable is asserted rather than floating, and R6/R7 put 100k from "
        "each gate to GND so the load is off while the MCU boots and if the "
        "drive is absent entirely. Gate rating: 10 V against the +-20 V this "
        "class carries, asserted with headroom on purpose, because the "
        "failure mode of a SHUNT rail is D5 missing and the full pack "
        "arriving at the gate through R9. Ringing: R4/R5 are 10R and sit "
        "4.90 mm from the driver's OUT pin, which is the end that damps. Two "
        "residuals, named rather than lumped: the FET is one of the 13 "
        "unsourced values, so Qg, Ciss and the exact Vgs maximum are bounded "
        "by the requirement string rather than read off a part; and R4 sits "
        "16.61 mm from Q1's gate, which is longer than a 4 A driver's output "
        "should run beside a switching drain -- that is placement work and is "
        "tracked with the rest of it under M13."
    ),
    "M25": (
        "all four parts, and the fourth is signed by turning the unknown into "
        "a REQUIREMENT rather than by waiting for it. "
        "Right net, measured: U1's exposed pad on GND as 'the major heat "
        "dissipation path of the die' requires, U2's pad 39 on GND, and -- the "
        "two that are NOT ground -- D2/D3's 101.5 mm2 tab is the CATHODE and "
        "sits on the VBAT pour, Q1/Q2's tab is the DRAIN and sits on its own "
        "pump pour. None floating. Vias: six plated 0.3 mm holes through U1's "
        "pad (KiCad's ThermalVias land, opened from 0.2 to the fab's 0.3 "
        "floor), which is why A8 is waived and stitch_exceptions lists U1.9 -- "
        "and U2's thermal pad has twelve of its own, which is what made the "
        "router's extra six redundant under M29. Paste in a windowpane, "
        "measured off the footprints: U1's exposed pad is 2.29 x 3.00 = 6.87 "
        "mm2 and carries four F.Paste openings of 0.96 x 1.25 = 4.80 mm2 "
        "total, 70 % coverage, inside the rule's 50-80 % -- and those same "
        "four dabs are what A12 was measuring as copper until it was fixed. "
        "THE JUNCTION TEMPERATURE, which was the part this item stayed open "
        "for. It could not be computed because the diode is unsourced, so "
        "neither Vf nor RthJC is a read number -- but that framing had the "
        "dependency backwards. Everything on the BOARD side is measurable now, "
        "and what comes out is the Vf the part must have, which is a better "
        "answer than a temperature: it goes into the value string and changes "
        "which part gets bought. "
        "Three corrections to the numbers this entry used to carry. (1) THE "
        "DUTY IS NOT THE USER'S, and nothing had read the firmware to find "
        "out. main.cpp states it: 'NO INTERMEDIATE DUTY. The stick is used "
        "hard-forward or hard-back, so engaged means RUN_DUTY and nothing "
        "else.' RUN_DUTY synthesises the pump's 12 V nameplate from the pack, "
        "so D = 12/Vpack and the diode carries the other (1-D). That inverts "
        "the intuition about which battery state is worst: a DRAINED 15 V pack "
        "runs D = 0.80 and the diode conducts 20 % of the time, a FRESH 20 V "
        "pack runs D = 0.60 and it conducts 40 %. The hot case is a full "
        "battery. (2) THE AVERAGE CURRENT WAS A ROUND NUMBER: CIRCUIT.md said "
        "'at 50 % duty it carries ~3.75 A average', from before the duty was "
        "derived. The worst case is 3.00 A, and it is LOWER than the old guess "
        "because the firmware will not run the pump at 50 %. (3) THE POUR WAS "
        "WRONG BY A FACTOR OF FIVE: this entry said '~130 mm2', which is "
        "PUMP_A_LO's 138.3. The tab is the CATHODE and sits on VBAT, which "
        "fills as one island of 687.0 mm2, and D2 and D3 never conduct "
        "together -- direction is chosen by which pump is energised -- so each "
        "sees the whole pour rather than half of it. "
        "The arithmetic, with its one assumption named. 687 mm2 of 1 oz copper "
        "puts a D2PAK at about 42 C/W junction to ambient by the standard "
        "pad-area curves; that is a STATED ASSUMPTION, not a reading, and it "
        "is the first number to replace when a part is chosen. Ambient is the "
        "sealed bay rather than the garden: 35 C outside plus the bay's own "
        "rise gives 50 C. Holding Tj <= 125 C allows (125-50)/42 = 1.79 W, and "
        "at 3.00 A average that is Vf <= 0.59 V at 7.5 A. The sensitivity is "
        "worth stating because the assumption is: at 50 C/W the ceiling falls "
        "to 0.50 V, at 35 C/W it rises to 0.71 V, so the part choice is not "
        "comfortable and a candidate's own RthJA is the number to check first. "
        "All of it is arithmetic in elec/main.py with an assert that the "
        "ceiling lands inside what a 60 V Schottky can physically be, so the "
        "figures cannot drift from the prose. "
        "The requirement travels with the part: the value is "
        "'SCHOTTKY-60V-15A-vf0V59' now, floored rather than rounded -- _house "
        "would have printed 0V6, which is a limit 0.005 V looser than the one "
        "the arithmetic produced, and a part sourced against the printed "
        "string would have been out of spec against the computed one. Same "
        "reasoning as L1's '10uH/4A6sat'. The value stays in "
        "elec/fab.py's OPEN_VALUES, because a requirement is still not a part "
        "number; what has changed is that it is now a requirement a "
        "distributor search can actually be run against."),
    "M26": (
        "fixed here, because the silk was a trap rather than a label. The "
        "nets were TXD0 and RXD0, landing on J6 pins that kicad_silk prints "
        "with their net names -- and every USB-UART adapter also labels its "
        "own pins TXD and RXD, from ITS point of view. Wire like to like and "
        "it is output into output: the board does not program, and nothing on "
        "either silk says why. The nets are now ESP_TX_TO_PROG and "
        "ESP_RX_FROM_PROG, which is this rule's own naming idiom, and the "
        "back silk reads '3 ESP_TX_TO_PROG / 4 ESP_RX_FROM_PROG' -- measured "
        "on the routed board, not intended. Both ends were read in their "
        "datasheets: module pins 34/35 keep the names RXD0/TXD0 because that "
        "is what Espressif calls them and what tools/check_pin_map.py ALIASes "
        "to IO3 and IO1, and pin 35 is U0TXD, an output, so the net called TX "
        "reaches exactly one transmitter. No other directional link exists on "
        "this board -- there is no SPI, no I2C and no second UART."
    ),
    "M27": (
        "every part on every strap, boot and debug net, listed out. EN: R3 to "
        "3V3, C8 to GND, J6 pin 5 -- a pull-up, a reset ramp and a header "
        "pin, which is the intended circuit and nothing else on it. IO0: J6 "
        "pin 6 and nothing else, so the module's own 45k pull-up decides boot "
        "mode and an open header leaves SPI Boot (M8). GPIO2, MTDI/GPIO12, "
        "MTDO/GPIO15 and GPIO5 carry NOTHING on this board -- no LED, no "
        "divider, no peripheral output, no pull of this board's own -- which "
        "is the strongest form this rule can be satisfied in, because a pull "
        "to the wrong rail cannot exist where there is no pull. The debug "
        "header has its six pins to itself. IO14 is used, for LEVEL, and it "
        "is MTMS: a JTAG pin, but NOT one of the five strapping pins, and "
        "this board programs over UART0 through J6 rather than over JTAG, so "
        "reusing it locks no programmer out."
    ),
    "M28": (
        "each multi-pin part's pinout is cited in quality.pinouts with the "
        "section it was read from, and tools/check_ic_pinouts.py compares "
        "those citations against the netlist AND counts pads, so the citation "
        "and the circuit cannot drift apart without that gate firing -- it is "
        "the gate that found the ESP32 two ground pins short. This rule's "
        "warning about makers earned itself on this board: 'UCC27517' is sold "
        "both by TI and as a UMW/UTD part, and on this circuit they are NOT "
        "interchangeable. TI SLUSAY4D 8.5 gives VIN_H 2.2 V typ / 2.4 V MAX "
        "with thresholds explicitly 'independent of the VDD supply voltage'; "
        "the UMW datasheet gives VIH 2.7 V MIN and a recommended VCC starting "
        "at 5.0 V rather than 4.5. An ESP32 guarantees only 0.8 x VDD = "
        "2.64 V of VOH, so the TI part has 240 mV of margin and the UMW part "
        "has MINUS 60 mV -- the pumps would work on a bench and be guaranteed "
        "nowhere. The suffix matters for a second reason already recorded in "
        "elec/fab.py: a UCC27516 is the inverting sibling and would run the "
        "pumps whenever the MCU was held in reset. Both are 'do not "
        "substitute' under M40."
    ),
    "M32": (
        "Phoenix's own drawings, with the pitch measured on the footprint "
        "rather than read off the part name. J1-J3 are MKDS 3/2-5,08 at "
        "5.08 mm, rated 24 A / 400 V / 2.5 mm2 -- against 7.5 A, which is "
        "31 % of contact rating and the reason the pump legs are 5.08 and not "
        "3.5 (CIRCUIT.md section 7: 3.5 mm parts run 8-10 A, too close to 7.5 "
        "to be comfortable). J4 is PT 1,5/5-3,5-H and J5 is PT 1,5/4-3,5-H at "
        "3.50 mm, carrying milliamps to a joystick and a level sensor. "
        "Push-in rather than screw on the signal pair deliberately: two "
        "motors are bolted to the same frame as this board and a screw clamp "
        "backs off under vibration. Every connector that carries a "
        "single-ended signal also carries a ground -- J4 has three GND pins, "
        "J5 two, J6 one. Residual, named and measured rather than lumped: the "
        "wire-entry FACE is measured off Phoenix's STEP for J4 (54 mm3 of "
        "material behind local +Y against 232 behind -Y, so +Y is the "
        "opening) and for J5 (43 against 185), but the MKDS model is a "
        "simplified block with no Y-axis bores and material symmetric within "
        "6 % at every depth, so J1-J3's face rests on the generator's own "
        "convention and not on a measurement. The 1:1 print this rule asks "
        "for is the thing that would settle it, and it has not been done -- "
        "that is the one part of M32 accepted as a decision rather than shown."
    ),
    "M33": (
        "+3V3: the ESP32 is effectively the whole budget, and Espressif "
        "specifies a minimum of 0.5 A from the external supply for its WiFi "
        "bursts (v2.1 table 14), plus a joystick divider and whatever J6 "
        "feeds -- declared as 0.6 A in power_paths. That is 30 % of the "
        "LMR14020's 2 A, so the 50 %-on-a-first-board margin holds with room "
        "over, and the inductor is sized against the regulator's limit rather "
        "than against this load (M14). VBAT: 7.5 A for one pump plus 0.3 A "
        "for the buck's input (~0.16 A at the flat end of the pack) and the "
        "level sensor's feed. It is 7.5 and not 15 because "
        "tools/check_pump_dirs.py is the gate that holds 'never both at "
        "once', so the rail is never asked for two pumps -- the budget "
        "depends on that gate and would be wrong without it. Against the "
        "connectors: 7.8 A through an MKDS 3's 24 A contact (M32). Those are "
        "the amps declared in power_paths, which is what A1 measures the "
        "copper against, and VBAT is declared as TWO entries because it "
        "carries two currents -- the old single 7.5 A entry demanded 3.18 mm "
        "of copper at U1's 1.95 x 0.60 mm VIN pad, which was unmeetable "
        "because it was false."
    ),
    "M34": (
        "both ends read in their own datasheets, and the margin is thinner "
        "than it looks. The crossing that matters is ESP32 -> UCC27517 IN+: "
        "Espressif guarantees VOH >= 0.8 x VDD = 2.64 V at a 3.3 V rail "
        "(v2.1 table 15, whose IOH row is itself specified at 'VOH >= "
        "2.64 V' with 40 mA available), against TI's VIN_H of 2.4 V MAX over "
        "-40 to 140 C (SLUSAY4D 8.5). That is 240 mV, and it only works "
        "because those thresholds are 'independent of the VDD supply "
        "voltage' -- running the driver's VDD at 10 V does not raise them, "
        "which is the fact the whole gate-drive scheme rests on. Low side: "
        "VOL <= 0.1 x VDD = 0.33 V against VIN_L 1.0 V MIN, 670 mV. See M28 "
        "for why this forbids the UMW part. The drivers do start: VGATE 10 V "
        "against a VON of 4.65 V max over temperature. Polarities, each read "
        "at both ends: IN- low = enabled (the non-inverting path, and the "
        "active-low enable asserted); the ESP32's EN is active-HIGH and R3 "
        "pulls it up; LEVEL is an open collector pulled up by R23, so LOW "
        "means liquid, MODE is shorted to GND to select the sensor's "
        "normally-closed mode, and the firmware's LEVEL_FULL_IS_LOW encodes "
        "exactly that (CIRCUIT.md section 4). No differential pair, no "
        "auto-direction level shifter and no op-amp feedback on this board."
    ),
    "M37": (
        "done, with gerbonara 1.6.3 -- an independent Gerber/Excellon reader that "
        "has never seen KiCad's internal model -- reading elec/out/fab/main/ and "
        "rendering it layer by layer to PNGs that were then looked at. This is the "
        "half of M37 that fab_package cannot do for itself: fab_package refills the "
        "zones, re-runs DRC, exports gerbers and drill from that one state and "
        "checks the drill back against the board, but every one of those reads the "
        ".kicad_pcb. This reads the FILES. "
        "What the second reader agrees about, RE-READ after the via work below "
        "changed the board (the first read's counts are not quoted here, because "
        "a sign-off that cites a superseded package is worse than one that "
        "cites none): the board is 95 x 100 on Edge_Cuts (12 objects -- four "
        "edges and four 4.6 mm corner circles); F.Cu 544 objects, B.Cu 198, "
        "F.Mask 208, F.Paste 178, B.Paste 0 (nothing is assembled on the "
        "back), F.Silk 2545, B.Silk 1116; main.drl parses as Excellon and "
        "holds 127 holes on four tools -- 0.300 x 104, 1.000 x 8, 1.200 x 9, "
        "1.300 x 6 -- every one declared Plated,PTH. That 127 is CROSS-CHECKED "
        "against the board rather than admired: 86 board vias plus 41 pad holes "
        "(0.300 x 18 -- twelve in U2's thermal pad and six in U1's exposed "
        "pad -- 1.000 x 8, 1.200 x 9, 1.300 x 6) is 127, and the per-tool "
        "counts agree one for one. Worth doing because the drill total did NOT "
        "move when nine vias were retired or shifted -- 127 before and 127 "
        "after, 104 of them at 0.300 mm both times -- which looks exactly "
        "like a stale package. It is not. The copper counts did move, F.Cu "
        "554 to 544 and B.Cu 191 to 198, and the board/drill cross-check "
        "above passes on the new one. What cancelled was two changes at once: "
        "unwick retired seven vias, and the same cadkit sync that exposed them "
        "also changed layout.py, route.py and close_last.py, so the route "
        "itself is not the route that produced the first package. "
        "⚠ THE FIRST EXPLANATION WRITTEN HERE WAS THAT THE ROUTER LAYS A "
        "DIFFERENT NUMBER EVERY RUN, AND THAT IS FALSE. Re-running main.py, "
        "finish.py and fab.py end to end returns byte-identical counts -- "
        "F.Cu 544, B.Cu 198, drill 127 -- so the route is reproducible for a "
        "given toolchain and the variance was in the TOOLCHAIN, not in the "
        "router. That matters beyond this paragraph: a reproducible route is "
        "what makes a count worth quoting in a sign-off at all. "
        "What the LOOK found, which is the point of the rule: the three "
        "high-current F.Cu pours fill where they were drawn and nowhere else -- "
        "VBAT's bus runs under J2|J1|J3 and up both risers into D2's and D3's "
        "cathode tabs, PUMP_A_LO and PUMP_B_LO stop short of the DPAK gate leads, "
        "and no pour reaches the joystick's pads or the board edge. Every drill "
        "hit lands inside its own pad. The four corner mounting holes carry NO "
        "drill hit, which is correct and was worth seeing: they are Edge_Cuts "
        "cutouts that the fab routs, which is what notes['cutouts'] asks for and "
        "what the geometry gate cross-checks as '4 cutout(s) match, 63.6 mm2 vs "
        "63.6'. "
        "The one thing the look found that nothing had measured is in M3's "
        "territory and is now its own gate. B.Cu is both the ground plane and a "
        "routing layer, so it is a plane with slots cut in it: 455.89 mm of signal "
        "copper across 13 nets, the longest single runs being PWM_B at 49.60 mm "
        "and PWM_A at 44.79 mm. Rendered, the plane under the whole power section "
        "-- Q1, Q2, D2, D3 and the three pours above them -- is solid and "
        "unbroken, which is the thing that mattered and had only ever been "
        "asserted. A13 now measures it for every signal on every board: 131 F.Cu "
        "tracks sampled every 0.25 mm, 18 straddled cuts, the widest 3.03 mm "
        "(BUZZ, two B.Cu tracks side by side) against a 5.0 mm limit. A13 was made "
        "to fail four ways before it was believed -- at a 3.0 mm limit it catches "
        "2 crossings, at 1.0 mm all 18, an exemption list drops BUZZ and hands "
        "back LEVEL at 3.01, and a board stripped of its ground pour gets a note "
        "and no claim at all. "
        "Two honest negatives. gerbonara's own filename autoguesser does not claim "
        "main.drl, which is named for the board rather than with a -PTH suffix, so "
        "the drill was opened explicitly by name; it parses clean either way, and "
        "KiCad marks it MixedPlating in its own header, which is the attribute a "
        "fab reads rather than the filename. And gerbonara warns that main.drl's "
        "G90 sits after the header's '%' -- read against the file, G90 is absolute "
        "mode restated in the body, which is what KiCad has always written and "
        "what every fab's loader expects; it changes no coordinate. "
        "The renders, and the scripts that made them, are the session scratchpad's "
        "render/ -- they are a measurement, not a build product, so they are not "
        "committed."),
    "M39": (
        "every input that is not used is terminated, and the module's own "
        "datasheet is what sanctions how. The ESP32's unused pins are module "
        "pins left open, which v2.1 table 4 states is precisely the condition "
        "under which the internal 45k pulls set the strapping values (M8) -- "
        "so they are HELD, not floating, and adding external pulls to them "
        "would be the error. J4's VRX and SW are the joystick's unused axis "
        "and its button, both tied to GND rather than left as one-pin nets. "
        "J5's MODE is tied to GND, which is not 'unused' but a configuration: "
        "it selects the sensor's normally-closed mode, and the vendor's "
        "warning is only against using that wire as the power RETURN in place "
        "of the blue one (CIRCUIT.md section 4). Both UCC27517 inputs are "
        "driven or tied -- IN+ from the MCU, IN- to GND -- neither floating, "
        "which the datasheet requires rather than suggests. No unused output "
        "on this board needs a load. Spare pins worth having later are the "
        "whole point of the ten bring-up pads (M9)."
    ),
    # ══ decide ══════════════════════════════════════════════════════════════
    "M35": (
        "read, and one of the two documents changed a rating this board "
        "depends on. ESP32: the ESP32 Series SoC Errata, against the pins and "
        "peripherals this board actually uses. APPLIES -- GPIO-3.6 (v3.0 and "
        "v3.1), the GPIO pull-up/pull-down CONFIGURATION REGISTER fields are "
        "nonfunctional on pads that are also RTC_GPIO, and IO14 is one of "
        "them while the firmware does pinMode(LEVEL_PIN, INPUT_PULLUP). So "
        "that internal pull may simply not be there, and R23's external 10k is "
        "what actually holds the open collector up; tools/check_pin_map.py's "
        "docstring already said the internal one 'is not a substitute for "
        "it', and this erratum is what makes that sentence load-bearing rather "
        "than cautious. DOES NOT APPLY, each for a reason worth keeping -- "
        "GPIO-3.11 pulls GPIO36 and GPIO39 down for ~80 ns when certain RTC "
        "peripherals power up, and this board's ADC inputs are IO34 and IO35, "
        "so moving them to 36/39 to 'tidy the pinout' would walk straight into "
        "it; GPIO-3.14 forbids mixing edge interrupts with others in a group, "
        "and the firmware has no attachInterrupt at all, it polls; LEDC-3.12 "
        "overflows the duty in DECREMENTAL FADE mode with the scale register "
        "at 1, and the pumps are driven by ledcAttach/ledcWrite with plain "
        "duty values and no fade API; CLK-3.22 is WiFi plus Ethernet and there "
        "is no Ethernet; ULP-3.19 needs deep sleep and the ULP, and the "
        "firmware uses neither; the TWAI errata need a CAN bus this board does "
        "not have; CPU-3.16/3.18/3.21 are address-space and FIFO access "
        "limitations the toolchain handles, with no board consequence. And one "
        "that is worth stating because it was assumed the wrong way round: "
        "RES-3.4, 'the Brown-out Reset function does not work', affects v0.0 "
        "ONLY -- so the ESP32-D0WD-V3 in this module does have working BOR, "
        "which matters because the output capacitance is sized against a "
        "brownout ceiling (M15). LMR14020: TI publishes no separate errata "
        "sheet for it, so the datasheet's own revision history is the record, "
        "and reading it earned its place -- revision A to B LOWERED two "
        "absolute maxima, BOOT-to-SW from 6.5 V to 5.5 V and FB-to-GND from "
        "7 V to 5.5 V, and moved RthJA from 42.5 to 43.2 C/W. Both tightened "
        "ratings are cleared here: C3 across BOOT-SW is a 100n/50V, and FB "
        "sits at 0.750 V nominal. A design checked against revision A would be "
        "checked against two numbers that no longer exist. No errata are "
        "published for the UCC27517 (SLUSAY4D is current) or for the WROOM "
        "module itself beyond the chip errata above."
    ),
    "M36": (
        "the one genuine safety finding in this pass, and it is fixed rather "
        "than decided away. Three supplies leave this board down a cable: "
        "+3V3 to J4 (the joystick) and J6 (the programmer), and VBAT to J5 "
        "(the level sensor). The 3V3 pair are limited by the regulator itself "
        "-- a short there drives the LMR14020 into its own 2.5/3.2/3.8 A "
        "current limit with short-circuit protection and frequency fold-back "
        "(SNVSAA5B 6.3), and the MCU resets. VBAT had nothing. That lead is "
        "the most exposed conductor in the machine: it leaves the sealed bay "
        "through the chase and then climbs the OUTSIDE of the case to the "
        "tank, so it is the one wire that gets rubbed, pinched and walked "
        "past -- and behind it is a Makita 18 V LXT pack that will put well "
        "over a hundred amps into a short. The killswitch at the dock is a "
        "SWITCH, not a fuse: it opens when a person opens it, not when a "
        "chafed sensor lead starts to glow. F1 is now a resettable PTC in "
        "series with J5.1, and resettable on purpose -- this machine is "
        "carried into a garden and a cartridge fuse out there is a walk home. "
        "0.2 A of hold current against a sensor drawing about 10 mA is twenty "
        "times headroom, so no nuisance trip from the inrush into C18, while "
        "still far under what damages the lead; 30 V is the common 1206 PPTC "
        "tier and clears a 20 V fresh pack. Both numbers are asserted. C18 "
        "went in with it because fusing the feed makes J5.1 a net of its own "
        "and A2 gives a connector 25 mm to its nearest charge -- what had been "
        "answering for J5 was C15, the BUCK's input ceramic 16.25 mm away, on "
        "VBAT by accident of placement and with a different job. Past the "
        "fuse is the right side for it anyway: F1 then sees the DC while the "
        "cable's inrush comes from C18, 9.76 mm away. C17 could not be moved "
        "up to do it, because C17 is J1's bypass at 24.0 mm and the next "
        "nearest pad to J1 is 27.5."
    ),
    "M21": (
        "the capacitor is AT the pin now, which is the clause this rule turns "
        "on, and it was 56.81 mm away. Measured on the routed board, pad to "
        "pad: C12 -- the joystick RC's capacitor, the only noise defence on an "
        "input fed by a hand-held stick on the end of a lead -- is 2.19 mm "
        "from U2.6 / IO34, against 56.81 before; C11 is 2.35 mm from "
        "U2.7 / IO35, against 28.04. The old placement left 57 mm of "
        "high-impedance track on the board OUTSIDE the filter, on the two "
        "signals that are the machine's entire input, under a comment in the "
        "placement block that said R21 and C11 'sit at the MCU'. R22 "
        "deliberately stays at the CONNECTOR end: with the resistor at J4 and "
        "the capacitor at the pin the whole board run sits inside the filter "
        "and its pickup is shunted by C12, where swapping them would put 1k at "
        "the pin and leave the run outside the pole. The floor on how close "
        "they can get is measured, not guessed -- U2's courtyard is one "
        "8-point outline covering the module body at y 9.22..28.71 plus the "
        "antenna keepout hanging off the laminate, so 28.71 plus an 0603's "
        "0.775 mm half-height is the limit and 29.9 leaves 0.415; placing them "
        "at 29.3 cost three courtyards_overlap against U2, which is how that "
        "outline came to be measured rather than assumed. A quiet ground: the "
        "ESP32 module has no separate analog ground pin to split, the B.Cu "
        "plane under both nets is one unbroken 8192 mm2 island (M3), and both "
        "pins are a long way from the switching -- 69.98 and 71.25 mm from the "
        "SW node, 64.20 mm from the inductor, 85.16 mm from Q1's drain. Both "
        "are on ADC1, because ADC2 is unusable while WiFi is up and this "
        "design has WiFi telemetry; tools/check_pin_map.py is the gate that "
        "keeps them there, and its docstring calls that the rule most likely "
        "to be broken by someone tidying the pinout."
    ),
    "M3": (
        "the return is a single unbroken plane, measured on the FILLED board "
        "rather than on the zone outlines. GND on B.Cu fills as ONE island of "
        "8192.1 mm2 on a 95 x 100 (9500 mm2) outline -- 86 % of the board, "
        "with no second island for a return to neck through. Every "
        "high-current supply path is a pour as well, and each of those is "
        "also one island: VBAT 687.0 mm2, PUMP_A_LO 138.3, PUMP_B_LO 127.2. "
        "So each 7.5 A path AND its return are planes, and the return is the "
        "wider of the two by better than an order of magnitude -- which is "
        "what this rule is actually asking. The sensitive reference does not "
        "share a narrow path with the pump current because there is no narrow "
        "path to share: the analog nets run over that same solid B.Cu (M21). "
        "Island counts are the measurement that matters here, because the "
        "first attempt at these pours filled perfectly into EIGHT islands "
        "that touched nothing, and the zone outlines looked right in every "
        "one of them."
    ),
    "M6": (
        "decided rather than skipped: there is nothing high-speed on this "
        "board to match or to give a reference. The fastest edge is the pump "
        "PWM at 20 kHz, then the buck's 500 kHz switch node, then UART0 at "
        "115200 baud on J6. No clocked parallel bus, no differential pair, "
        "nothing above ~50 MHz on the board at all -- the ESP32's radio is "
        "inside the module, which is why its antenna is a PLACEMENT question "
        "(the open item in CIRCUIT.md about it facing the pack) and not a "
        "routing one. So there is no match group to budget a skew for, and no "
        "layer change to put a ground via beside. The reference is unbroken "
        "in any case: M3."
    ),
    "M9": (
        "ten bare 1.5 mm pads, one per question you ask when a board arrives "
        "and does not work, and each LABELLED with its net name by "
        "cadkit/kicad_silk.py -- a bring-up note saying 'probe VGATE' is no "
        "help if the board does not say which pad that is. Measured on the "
        "finished board, all ten placed, all at 1.0 mm text: GND (the "
        "reference for every other probe, and the one a clip can reach), "
        "VBAT, +3V3, VGATE, SW, GATE_A, GATE_B, VBAT_SENSE, JOY_FILT, LEVEL. "
        "That is every rail and every signal the bring-up order needs, in the "
        "order you would ask -- did the pack reach the board, did the buck "
        "start and at what voltage (which also sets the ADC's full scale, so "
        "it explains the other readings), did the Zener rail come up, is it "
        "switching and at what frequency, is the driver driving or is the FET "
        "dead, what does the ADC actually see against what the divider says. "
        "Programming, reset and boot are on J6. Each pad is SEARCHED for a "
        "site already sitting on its own net's copper, against the finished "
        "board, so not one of them adds a track."
    ),
    "M10": (
        "decided, with the distance measured rather than waved at. The TVS is "
        "37.71 mm from J1.1, and C2 and C1 are NEARER the terminal at 26.68 "
        "and 28.91 mm -- so this board does not satisfy the rule's 'nearer "
        "its pins than any capacitor on the same line', and saying otherwise "
        "would be false. What that costs is the inductance between the "
        "terminal and the clamp, perhaps 20-30 nH across the VBAT pour. It is "
        "accepted because of what the threats on THIS machine are: the board "
        "is sealed inside the housing with no connector a hand can reach, and "
        "its two real transients -- the pump legs' inductive kick at 20 kHz "
        "and the ring when the Makita pack is docked -- are microsecond "
        "events, where 30 nH is nothing. The case where 30 nH would decide "
        "the outcome is a nanosecond ESD strike at an exposed pin, and there "
        "is no exposed pin. Reverse polarity is not protected and does not "
        "need to be: the pack cannot be docked backwards. Over-current "
        "protection is a different answer -- see M36, which is open, not "
        "decided."
    ),
    "M11": (
        "the CAD gates are the measurement, and they are the ones that have "
        "caught this before. tools/check_overlaps.py reports 0 mm3 of "
        "housing-to-PCB interference on the mated envelope -- it is the gate "
        "that found 1.17 mm3 of J2's VBAT solder tail sitting on a standoff "
        "boss, which is why all four mounting holes moved to +-43 mm. Every "
        "field cable leaves the board's -Y edge, which faces down into "
        "CHASE_Y0..Y1, the bay's only opening, and each terminal's wire-entry "
        "face points into it; J1-J4 sit 20 mm above the chase and drop into "
        "it, and J5's lead runs down the outside of the case (CIRCUIT.md "
        "section 7, which also withdraws two earlier notes that had the "
        "rotations backwards). finish.py's own CAD cross-check passes: 62 "
        "footprints, 4 cutouts matching to 63.6 mm2 against 63.6, and 52 of "
        "52 routed parts where the CAD draws them. Parts the fab cannot "
        "place are not zero and are not hidden: the five terminal blocks and "
        "J6 are through-hole, hand-soldered by the same call already made for "
        "the KY-023, and M30 is where that has to be priced."
    ),
    "M20": (
        "decided: there is nothing on this board to terminate. No I2C, no "
        "CAN, no clock leaving a pin, so neither of the I2C bounds nor the "
        "two-120R rule has a subject. Every pull on the board is a single one "
        "and each is there for a stated reason -- R3 10k on EN with C8 for "
        "the reset ramp, R23 10k pulling up the level sensor's open "
        "collector, R6/R7 100k pulling each gate down. None is doubled: the "
        "five strapping pins are held by the module's own 45k internal pulls "
        "and this board adds nothing to them (M8, M27). The one deliberate "
        "double is LEVEL, where the firmware also sets INPUT_PULLUP -- "
        "parallel pull-ups, harmless, and the EXTERNAL one is what keeps the "
        "sensor's 18 V rail off the pin, so the internal one is not a "
        "substitute for it. tools/check_pin_map.py records that in its own "
        "docstring so the next person does not 'tidy' R23 away."
    ),
    "M22": (
        "no op-amp, comparator or amplifier section exists on this board, so "
        "there is none to leave floating, to short the inputs of, or to run "
        "outside a common-mode range. The only analog signals are two divided "
        "or filtered DC levels into the ESP32's own ADC1 (M21), and the two "
        "inputs of each UCC27517 -- which are logic inputs with fixed TTL "
        "thresholds, not analog ones, and both are driven or tied (M7, M34, "
        "M39)."
    ),
    "M29": (
        "both halves done, and the via-in-pad half was wrong in this file in "
        "three separate ways before it was measured properly -- which is "
        "recorded here because the shape of the error is the useful part. "
        "The fab-table half: A12 is green, the capability table is dated "
        "2026-10-04 for the service being ordered (JLCPCB standard 1 oz, 2 "
        "layer), and the tightest different-net SMD copper gap on the board "
        "is 0.350 mm at U3.1 VGATE to U3.2 GND on the SOT-23-5 driver, "
        "against a 0.15 mm floor -- 2.3x. "
        "The via-in-pad half. (1) THE SIZES WERE WRONG: this entry called "
        "Q1.3 and Q2.3 '0.96 x 1.25 mm DPAK source leads'. Measured, they are "
        "2.20 x 1.20, and layout.py's stitcher put its vias there on purpose "
        "because they clear its via_d + 0.6 threshold. (2) THE METRIC WAS "
        "WRONG: ranking by pad AREA, the worst via in a land reads 8 % and "
        "looks like nothing. The number that decides a starved joint is "
        "VOLUME -- an open 0.3 mm barrel through 1.6 mm of laminate holds "
        "0.113 mm3, and the paste printed on an 0603 land is 0.855 mm2 x "
        "0.12 mm of foil = 0.103 mm3. The barrel can take MORE than the whole "
        "deposit: 110 %, not 8 %. On that ranking the three this entry named "
        "were not the three that mattered -- C12.2 at 110 % was never "
        "mentioned, and Q1.3/Q2.3 sit at 36 %. (3) THE CULPRIT WAS WRONG: the "
        "entry proposed stitch_exceptions as the mechanism, which suppresses "
        "a STITCHER via. Four of the ten (C6.2, C12.2, C15.2, C16.2) had "
        "tracks attached, so the ROUTER put them there, and the stitcher's "
        "threshold has no authority over the router at all. "
        "What the gerber look added, and it is the reason none of this was "
        "visible: the board model calls every one of those vias TENTED -- "
        "KiCad reports IsOnLayer(F_Mask) false for all of them, because it "
        "adds no mask opening of their own. The PAD's aperture is already "
        "open over them. The exported F.Mask settles it: 208 dark flashes, "
        "exactly one per pad on the layer, and zero clear flashes anywhere, "
        "so there is no mask island inside any aperture and every barrel in a "
        "land is open under the paste. "
        "Fixed, not decided away. cadkit/pcbflow/unwick.py now runs after "
        "routing and before the refill: it moved C15.2's via 1.20 mm and "
        "C16.2's 1.30 mm, insisting on a mask dam between via and land (a via "
        "stopping 0.1 mm short of the pad leaves no room for mask and the "
        "joint simply flows sideways instead of down), and it refuses a move "
        "longer than 1.5 mm -- the uncapped first run put C12's via 4.00 mm "
        "away, and C12 is the ADC filter capacitor placed 2.19 mm from the "
        "pin it filters on purpose, so that cure was worse than the disease. "
        "C12.2 was then RETIRED instead: the router had dropped two vias on "
        "that pad and the other sits 1.03 mm away, outside the land, joined "
        "by 0.97 mm of F.Cu. Retirement is narrow by construction -- only a "
        "net the design declares a plane in stitch_nets, only with a keeper "
        "within 2 mm that is itself outside every land, and finish.py re-runs "
        "DRC and the unconnected count immediately after (0 and 0). "
        "One more defect came out of the fix and is worth recording: "
        "unwick's first clearance check skipped same-net copper, so it parked "
        "C16.2's via 0.165 mm into another GND via. Electrically nothing "
        "shorts; mechanically the drill cannot make it, and A12 caught it as "
        "hole-to-hole. A hole is a hole whatever net it is on. "
        "A14 now measures the outcome on every board rather than trusting the "
        "stitcher's intent, and was made to fail four ways: a 0.05 mm stencil "
        "prints less paste and three lands go over half, a 2.4 mm board "
        "deepens the barrel and two do, declaring Q2.3 filled-and-capped "
        "hands back Q1.3 in its place, and a board with no paste at all gets "
        "a note and no claim. As built the board passes with six vias left in "
        "pasted lands, the thirstiest being Q2.3 at 36 % -- under half, so "
        "the joint still forms, and those six are where layout.py means them "
        "to be. "
        "A cadkit sync then landed a WIDER A12 (12 checks to 15), and its new "
        "pad-hole-to-hole measurement found a second family of the same defect "
        "that nothing here had looked for: U2's thermal pad is 21 pad objects "
        "-- nine 0.90 mm SMD lands and TWELVE 0.70 mm PLATED HOLES on a 0.700 "
        "mm grid, the module's own thermal via array -- and the router had "
        "dropped its own GND vias into it. Ten places from 0.416 mm of gap "
        "down to 0.000, that last one two 0.3 mm barrels exactly tangent, "
        "which the drill cannot make as two holes. The first unwick pass "
        "walked straight past all ten, because it only looks at lands small "
        "enough to STARVE and this pad is enormous. unwick has a second pass "
        "now, on the different trigger: a hole drilled inside the fab's "
        "hole-to-hole minimum of another hole. Six GND vias were retired from "
        "that pad, each with a same-net plated barrel 1.40 to 1.88 mm away "
        "that is not in violation -- and the keeper may be a PAD hole here, "
        "not only a via, because a plated barrel reaches the plane whichever "
        "object owns it. They were redundant from the moment they were laid: "
        "the pad they sit in is on GND and already has twelve barrels of its "
        "own."),
    "M31": (
        "measured on the finished board rather than asserted, and it was not "
        "true before. All 17 board-level silk items are at 1.0 mm height and "
        "0.15 mm stroke, and ZERO are under the fab's minimum -- which is the "
        "whole point, because JLCPCB's standard font needs >= 1.0 mm and its "
        "own page says its engineering team 'will not adjust the character "
        "height in the files'. 0.8 mm is the high-precision tier, which also "
        "wants a finer stroke, so the 16 labels that used to sit at 0.8 mm "
        "and 0.15 were in neither tier and would have printed as drawn with "
        "nobody saying so. A12 measures this every run now. The board's name "
        "and revision are on it ('MAIN r1', 1.5 mm, front). Every connector a "
        "person wires carries its signal names on B.Silk, with direction "
        "where it is not obvious (M26). Pin-1 and polarity marks come from "
        "the stock footprints and sit outside the part bodies (M2). Nothing "
        "is over a pad, a hole or the edge: the fitter holds 0.20 mm to any "
        "mask opening and 0.40 mm to the outline, and DRC reports no silk "
        "violation on the board."
    ),
    "M38": (
        "the housing gate is the measurement. tools/check_overlaps.py reports "
        "0 mm3 between the PCB and the housing on the mated envelope, so "
        "nothing sits under a screw head, a washer or a standoff -- it is the "
        "gate that caught J2's solder tail on a boss (M11). The two 1206 "
        "parts and the two 10 x 10.5 mm electrolytics are inboard of the "
        "mounting holes at +-43 mm, there is no break-off tab and no V-score "
        "on this outline, and the board is screwed at four corners rather "
        "than flexed across a span. Access: every field cable leaves the one "
        "-Y edge into the chase with 20 mm of drop, the terminals are "
        "wire-entry so a screwdriver and a finger reach them from that "
        "opening, and the ten bring-up pads are bare 1.5 mm circles on the "
        "front face, reachable with the lid off. Strain relief is "
        "deliberately NOT at the terminals -- they provide none, which is why "
        "it is at the housing's buttress rib and its 10 x 7 mm tie slot, and "
        "why CIRCUIT.md section 7 says to tie the bundle to the rib and not "
        "to the terminals. The four mounting holes are deliberately isolated: "
        "laminate all round, no copper and no net on any of them."
    ),
    "M40": (
        "every value on the board is one that can be bought: 29k4 and 49k9 "
        "are E96, and the rest are E24 or better -- 100k, 18k, 10k, 1k5, 1k, "
        "10R. The parts chosen FOR a parameter say so where they are defined, "
        "which is this rule's real ask, and on this board several of them say "
        "it in the value string itself so that the requirement cannot be "
        "separated from the part. Q1/Q2 and D2/D3 carry theirs that way -- "
        "NFET-60V-10mR and SCHOTTKY-60V-15A -- because both previously "
        "carried a part NUMBER that did not meet the requirement: a 40 V "
        "AOD4184A under a 38.9 V clamp, and an SS16H, a 1 A SMA diode, on a "
        "7.5 A leg in a D2PAK land. L1's value is 10uH/4A6sat, derived from "
        "the saturation current the asserts check (M14). U3/U4 must be the TI "
        "UCC27517 -- not the UMW part, whose VIH minimum the ESP32 cannot "
        "guarantee, and not the inverting UCC27516, which would run the pumps "
        "whenever the MCU was held in reset -- and elec/fab.py records both "
        "reasons beside the open value. C4 and C19 must be X7R or better, "
        "which is a do-not-substitute of a different shape -- the value "
        "'22u/16V' does not state a dielectric, and the whole stability "
        "argument for the output capacitance is a 0.6 bias derate that only "
        "an X7R keeps (a Y5V of the same marking can lose 80 % and land under "
        "the requirement, with nothing in any gate to notice). See M15. The "
        "tabs that are electrically LIVE "
        "are written down where the parts are defined: D2/D3's 101.5 mm2 tab "
        "is the CATHODE and sits on the VBAT pour, Q1/Q2's tab is the DRAIN "
        "and sits on its own pump pour. Neither is ground and neither is "
        "floating by accident (M25). No part on this board needs a heatsink."
    ),
}

# Entries written as None are placeholders for items whose evidence lives in
# OPEN; strip them so the quality pass sees an unsigned item rather than a
# signature with no content behind it.
MANUAL = {k: v for k, v in MANUAL.items() if v}

assert not (set(MANUAL) & set(OPEN)), (
    "an item is both signed and open: %s" % sorted(set(MANUAL) & set(OPEN)))
